### ISSUE TITLE
Finite difference approximation implementation

### ISSUE THREAD

**Issue by PierreSue** [quark0/darts#11]
I traced the codes and noticed that there doesn't exist the part, "Fortunately, the
complexity can be substantially reduced using the finite difference approximation.", which is described in the paper. Has that been implemented?

Thanks

**Comment by bkj** [comment]
Yes it's implemented in `cnn/architect.py` in the `_hessian_vector_product` function

**Comment by PierreSue** [comment]
Thank you so much. I found that. By the way, the default unrolled is false, so it doesn't activate the approximation, does it.

**Comment by quark0** [comment]
Your understanding is correct.
