### ISSUE TITLE
How to extract the result cell structure of train_search.py?

### ISSUE THREAD

**Issue by kandysoso** [quark0/darts#126]
I figured that train.py use genotype.py to generate network. 
Train_search.py gives us weights.pt. So how to extract cell structure from this result?
Please tell me guys, thanks!

**Comment by cristikat** [comment]
Hi @kandysoso ,
If you print the genotype, you should be able to see the cell structure.

Cheers!

**Comment by kandysoso** [comment]
> Hi @kandysoso ,
> If you print the genotype, you should be able to see the cell structure.
> 
> Cheers!

Thank you！Could you please tell me more like how to print the genotpye? I'm a beginner

**Comment by kandysoso** [comment]
> Hi @kandysoso ,
> If you print the genotype, you should be able to see the cell structure.
> 
> Cheers!

thank you!
