### ISSUE TITLE
how about  stem_multiplier do?

### ISSUE THREAD

**Issue by JsBlueCat** [quark0/darts#13]
dear author,i'm very fascinated with your approach,But i'm a beginer on pytorch&architecture search.
when i am reading your source code, then come up with a question.
that is how about stem_mutiplier&mutiplier do? i mean in the 63th line of  your model_search.py file.
Is these things talked in your paper or another papar? 
Can you give me any suggestion?

**Comment by quark0** [comment]
If the input nodes have `32` channels, then there will be `multiplyer*32` channels in the output of the cell. `stem_multiplier` is the multiplyer for the preprocessing layer at the very beginning of the network.
