### ISSUE TITLE
Is this a normal case?

### ISSUE THREAD

**Issue by mrk1992** [quark0/darts#133]
I run this command

`python train_search.py`

and get a these results

![image](https://user-images.githubusercontent.com/11848064/74133302-a2642c00-4c2b-11ea-8aff-a229422057dc.png)

Is it right ?

**Comment by AlexeyGB** [comment]
I have the same problem. It seems that something is wrong with torch Dataloader's multiprocessing. At least setting `num_workers=0` for both `train_queue` and `valid_queue` makes the script work properly for me. But this crutch can not be considered as a satisfactory solution.

**Comment by mrk1992** [comment]
https://github.com/yuhuixu1993/PC-DARTS/issues/31#issuecomment-585484767

**Comment by mrk1992** [comment]
@AlexeyGB 
Go to https://github.com/yuhuixu1993/PC-DARTS/issues/31#issuecomment-585484767
