### ISSUE TITLE
Models trained using code in table 3

### ISSUE THREAD

**Issue by karandwivedi42** [quark0/darts#15]
In table 1, you have results for running NASNet/AmoebaNet models using your code (marked with `+`). Did you do similar experiments for Table 3 (Imagenet)?

If not, is running `train_imagenet.py` with `--arch=AmoebaNet` enough to get me ~26/27% error as reported?

Thanks :)

**Comment by quark0** [comment]
No we didn't try it. It may or may not be better due to the discrepancies between different implementations (though we've tried our best to mimic their training setup). I'm actually also curious and will launch some experiments when I get a chance.

**Comment by karandwivedi42** [comment]
Thanks! I was going to run so thought it might be useful to ask.
