### ISSUE TITLE
Doubt in the paper

### ISSUE THREAD

**Issue by meghbhalerao** [quark0/darts#150]
Dear Authors,
Thanks a lot for making the code open source. I have a doubt in the paper, in _equation 7_, when we apply the chain rule, I have 2 questions:
1. I think there is a typo in the first **dell operator**, I think it should be Dell with respect to **w'** and not wrt **alpha**, because of the chain rule variable substitution. 
2. When we apply the chain rule, there is a term **dell wrt alpha applied to w** , how did that come out to be 1? 
Megh

**Comment by buttercutter** [comment]
I am not sure if you had seen https://mythrex.github.io/math_behind_darts/ or [issue #69](https://github.com/quark0/darts/issues/69)

**Comment by meghbhalerao** [comment]
thanks a lot for he link. it was very helpful
