### ISSUE TITLE
Out of memory trying to run CIFAR example

### ISSUE THREAD

**Issue by AlexMikhalev** [quark0/darts#16]
I am tring to run CIFAR example using pyro docker image, but I have cuda out of memory error:

`pyromancer@6d7a480a66c9:~/workspace/shared/darts/cnn$ python train_search.py --unrolled
Experiment dir : search-EXP-20180712-214257
07/12 09:42:57 PM gpu device = 0
07/12 09:42:57 PM args = Namespace(arch_learning_rate=0.0003, arch_weight_decay=0.001, batch_size=64, cutout=False, cutout_length=16, data='../data', drop_path_prob=0.3, epochs=50, gpu=0, grad_clip=5, init_channels=16, layers=8, learning_rate=0.025, learning_rate_min=0.001, model_path='saved_models', momentum=0.9, report_freq=50, save='search-EXP-20180712-214257', seed=2, train_portion=0.5, unrolled=True, weight_decay=0.0003)
07/12 09:43:00 PM param size = 1.930618MB
Files already downloaded and verified
Files already downloaded and verified
07/12 09:43:01 PM epoch 0 lr 2.500000e-02
07/12 09:43:01 PM genotype = Genotype(normal=[('avg_pool_3x3', 0), ('dil_conv_5x5', 1), ('dil_conv_3x3', 1), ('dil_conv_5x5', 2), ('max_pool_3x3', 1), ('avg_pool_3x3', 0), ('dil_conv_5x5', 1), ('avg_pool_3x3', 0)], normal_concat=range(2, 6), reduce=[('avg_pool_3x3', 1), ('avg_pool_3x3', 0), ('sep_conv_3x3', 1), ('dil_conv_5x5', 2), ('sep_conv_3x3', 2), ('avg_pool_3x3', 3), ('max_pool_3x3', 4), ('dil_conv_5x5', 0)], reduce_concat=range(2, 6))
tensor([[ 0.1249,  0.1249,  0.1252,  0.1251,  0.1250,  0.1250,  0.1250,
          0.1249],
        [ 0.1250,  0.1248,  0.1251,  0.1250,  0.1250,  0.1250,  0.1251,
          0.1251],
        [ 0.1250,  0.1250,  0.1250,  0.1250,  0.1250,  0.1250,  0.1251,
          0.1249],
        [ 0.1249,  0.1249,  0.1249,  0.1250,  0.1249,  0.1250,  0.1253,
          0.1251],
        [ 0.1249,  0.1251,  0.1251,  0.1250,  0.1249,  0.1249,  0.1249,
          0.1251],
        [ 0.1250,  0.1250,  0.1252,  0.1251,  0.1249,  0.1249,  0.1250,
          0.1249],
        [ 0.1249,  0.1253,  0.1250,  0.1248,  0.1248,  0.1251,  0.1251,
          0.1250],
        [ 0.1249,  0.1251,  0.1251,  0.1252,  0.1250,  0.1248,  0.1250,
          0.1249],
        [ 0.1251,  0.1250,  0.1250,  0.1250,  0.1249,  0.1251,  0.1249,
          0.1250],
        [ 0.1249,  0.1248,  0.1252,  0.1247,  0.1251,  0.1249,  0.1252,
          0.1251],
        [ 0.1249,  0.1249,  0.1251,  0.1250,  0.1248,  0.1250,  0.1249,
          0.1254],
        [ 0.1251,  0.1250,  0.1250,  0.1250,  0.1252,  0.1250,  0.1249,
          0.1250],
        [ 0.1251,  0.1249,  0.1250,  0.1250,  0.1251,  0.1249,  0.1250,
          0.1251],
        [ 0.1251,  0.1252,  0.1251,  0.1247,  0.1252,  0.1249,  0.1249,
          0.1250]], device='cuda:0')
tensor([[ 0.1251,  0.1251,  0.1251,  0.1250,  0.1247,  0.1250,  0.1251,
          0.1250],
        [ 0.1250,  0.1249,  0.1251,  0.1250,  0.1250,  0.1248,  0.1251,
          0.1248],
        [ 0.1252,  0.1251,  0.1250,  0.1250,  0.1249,  0.1249,  0.1250,
          0.1250],
        [ 0.1248,  0.1249,  0.1250,  0.1249,  0.1252,  0.1250,  0.1251,
          0.1251],
        [ 0.1252,  0.1249,  0.1250,  0.1250,  0.1250,  0.1249,  0.1250,
          0.1251],
        [ 0.1249,  0.1251,  0.1250,  0.1250,  0.1250,  0.1251,  0.1250,
          0.1249],
        [ 0.1249,  0.1249,  0.1251,  0.1251,  0.1246,  0.1251,  0.1251,
          0.1251],
        [ 0.1250,  0.1247,  0.1250,  0.1251,  0.1252,  0.1250,  0.1250,
          0.1250],
        [ 0.1252,  0.1249,  0.1252,  0.1247,  0.1249,  0.1251,  0.1250,
          0.1250],
        [ 0.1248,  0.1251,  0.1251,  0.1249,  0.1249,  0.1249,  0.1251,
          0.1252],
        [ 0.1249,  0.1250,  0.1250,  0.1251,  0.1251,  0.1251,  0.1249,
          0.1249],
        [ 0.1250,  0.1249,  0.1249,  0.1252,  0.1250,  0.1250,  0.1251,
          0.1250],
        [ 0.1249,  0.1251,  0.1249,  0.1251,  0.1252,  0.1250,  0.1248,
          0.1250],
        [ 0.1251,  0.1253,  0.1249,  0.1250,  0.1248,  0.1249,  0.1248,
          0.1251]], device='cuda:0')
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/generic/THCStorage.cu line=58 error=2 : out of memory
Traceback (most recent call last):
  File "train_search.py", line 200, in <module>
    main() 
  File "train_search.py", line 124, in main
    train_acc, train_obj, arch_grad_norm = train(train_queue, search_queue, model, architect, criterion, optimizer, lr)
  File "train_search.py", line 152, in train
    arch_grad_norm = architect.step(input, target, input_search, target_search, lr, optimizer, unrolled=args.unrolled)
  File "/home/pyromancer/workspace/shared/darts/cnn/architect.py", line 37, in step
    input_train, target_train, input_valid, target_valid, eta, network_optimizer)
  File "/home/pyromancer/workspace/shared/darts/cnn/architect.py", line 53, in _backward_step_unrolled
    model_unrolled = self._compute_unrolled_model(input_train, target_train, eta, network_optimizer)
  File "/home/pyromancer/workspace/shared/darts/cnn/architect.py", line 23, in _compute_unrolled_model
    loss = self.model._loss(input, target)
  File "/home/pyromancer/workspace/shared/darts/cnn/model_search.py", line 110, in _loss
    logits = self(input)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/pyromancer/workspace/shared/darts/cnn/model_search.py", line 104, in forward
    s0, s1 = s1, cell(s0, s1, weights)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/pyromancer/workspace/shared/darts/cnn/model_search.py", line 54, in forward
    s = sum(self._ops[offset+j](h, weights[offset+j]) for j, h in enumerate(states))
  File "/home/pyromancer/workspace/shared/darts/cnn/model_search.py", line 54, in <genexpr>
    s = sum(self._ops[offset+j](h, weights[offset+j]) for j, h in enumerate(states))
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/pyromancer/workspace/shared/darts/cnn/model_search.py", line 22, in forward
    return sum(w * op(x) for w, op in zip(weights, self._ops))
  File "/home/pyromancer/workspace/shared/darts/cnn/model_search.py", line 22, in <genexpr>
    return sum(w * op(x) for w, op in zip(weights, self._ops))
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/generic/THCStorage.cu:58`

Card is GeForce GTX 1080  8119MiB  on ubuntu linux box.

**Comment by AlexMikhalev** [comment]
TITAN X card fixed the issue.

**Comment by AlexMikhalev** [comment]
07/12 09:56:00 PM train 000 2.394935e+00 17.187500 45.312500
07/12 09:56:53 PM train 050 1.983369e+00 26.164217 81.127457
07/12 09:57:46 PM train 100 1.866709e+00 30.244431 84.096535
07/12 09:58:39 PM train 150 1.794865e+00 32.895283 85.709854
07/12 09:59:32 PM train 200 1.729609e+00 35.704288 86.986938
07/12 10:00:25 PM train 250 1.681173e+00 37.630730 87.879730
07/12 10:01:17 PM train 300 1.635046e+00 39.503738 88.631645
07/12 10:02:10 PM train 350 1.594318e+00 41.150284 89.400818
07/12 10:02:53 PM train_acc 42.503998
train_search.py:181: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  input = Variable(input, volatile=True).cuda()
train_search.py:182: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  target = Variable(target, volatile=True).cuda(async=True)
train_search.py:189: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  objs.update(loss.data[0], n)
train_search.py:190: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  top1.update(prec1.data[0], n)
train_search.py:191: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  top5.update(prec5.data[0], n)
07/12 10:02:54 PM valid 000 1.367113e+00 48.437500 95.312500
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/generic/THCStorage.cu line=58 error=2 : out of memory
Traceback (most recent call last):
  File "train_search.py", line 200, in <module>
    main() 
  File "train_search.py", line 128, in main
    valid_acc, valid_obj = infer(valid_queue, model, criterion)
  File "train_search.py", line 184, in infer
    logits = model(input)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/pyromancer/workspace/shared/darts/cnn/model_search.py", line 104, in forward
    s0, s1 = s1, cell(s0, s1, weights)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/pyromancer/workspace/shared/darts/cnn/model_search.py", line 54, in forward
    s = sum(self._ops[offset+j](h, weights[offset+j]) for j, h in enumerate(states))
  File "/home/pyromancer/workspace/shared/darts/cnn/model_search.py", line 54, in <genexpr>
    s = sum(self._ops[offset+j](h, weights[offset+j]) for j, h in enumerate(states))
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/pyromancer/workspace/shared/darts/cnn/model_search.py", line 22, in forward
    return sum(w * op(x) for w, op in zip(weights, self._ops))
  File "/home/pyromancer/workspace/shared/darts/cnn/model_search.py", line 22, in <genexpr>
    return sum(w * op(x) for w, op in zip(weights, self._ops))
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/generic/THCStorage.cu:58

no, even on TITAN V CNN example crashes

**Comment by quark0** [comment]
Are you using pytorch 0.4? If so, you may refer to #14.

**Comment by JsBlueCat** [comment]
@AlexMikhalev 
I have met the same problem, when i use TITAN v with cuda 9.1 pytorch = 0.4.0 torchvision = 0.2.1, it throws out the error that gc object that already tracked.then i look up to the source code. i found that  gc in python is base on queue, which will lead to circular references.
to fix this problem, you can degrade  your torchvision and  pytorch  version  to 0.2.0  0.3.1
you can use this command,which is already work for me
pip install http://download.pytorch.org/whl/cu91/torch-0.3.1-cp36-cp36m-linux_x86_64.whl 
pip intall torchvision==0.2.0

i'am trying to solve this problem with pytorch 0.4.0. but it's really time-comsuming project.

**Comment by JsBlueCat** [comment]
when i wrap it into torch.no_grad(),it seems work.but  i don't completely do the experiment , because it really needs much time :(  ,  but i am sure it works well with pytorch 0.3.1

**Comment by JsBlueCat** [comment]
@quark0           
for i in range(self._steps):#0 1 2 3
            for j in range(2+i):# 0 1 ,  0 1 2,  0 1 2 3, 0 1 2 3 4 
                stride = 2 if reduction and j < 2 else 1
                op = MixedOp(C, stride)
                self._ops.append(op)

**Comment by quark0** [comment]
Because the first two nodes are the inputs—we reduce the spatial resolution only for nodes that are adjacent to the input nodes. I'm closing the issue but feel free to reopen it if you still get OOM.

**Comment by AlexMikhalev** [comment]
@quark0 do you plan to make darts pytorch 0.4 compatible?
