### ISSUE TITLE
RuntimeError: cuda runtime error (2) : out of memory at /tmp/pip-ba6igt7v-build/aten/src/THC/generic/THCStorage.cu:58

### ISSUE THREAD

**Issue by tleishilacy** [quark0/darts#22]
Hello, 
I am currently in Nivida GP104, Cuda compiler driver. Python 3.6.5, pytorch 0.3.1.

When I was trying to run train.py and train_search.py. It gave the error with:

RuntimeError: cuda runtime error (2) : out of memory at /tmp/pip-ba6igt7v-build/aten/src/THC/generic/THCStorage.cu:58

Any solutions for this error?

Thankyou

**Comment by quark0** [comment]
#18 is my best guess. FYI, the implementation was tested using cuda 9.0 and cudnn 7.

**Comment by tleishilacy** [comment]
How long have you guys been running out the result?
I reduce the batchsize to 40, and it has been running for almost the whole day.

**Comment by tleishilacy** [comment]
How long have you guys been running out the result?
I reduce the batchsize to 40, and it has been running for almost the whole day.

**Comment by quark0** [comment]
On a GTX 1080Ti it took 1.5 days to complete 600 epochs with batch size 96. You may need at least 2-3 days with batch size 40.
