### ISSUE TITLE
sharing batchnorm modules across nodes inside a rnn cell?

### ISSUE THREAD

**Issue by leckie-chn** [quark0/darts#28]
It is noticed that the batchnorm layer in DARTCellSearch is initialized once(https://github.com/quark0/darts/blob/d922492be3c71b33be98c7e35871013e0e761286/rnn/model_search.py#L14) but used multiple times (https://github.com/quark0/darts/blob/d922492be3c71b33be98c7e35871013e0e761286/rnn/model_search.py#L18, https://github.com/quark0/darts/blob/d922492be3c71b33be98c7e35871013e0e761286/rnn/model_search.py#L39)
so what's the point of it? Will there be any difference if I don't?

**Comment by quark0** [comment]
This is fine during the architecture search of RNNs where we neither use the global EMA stats nor learnable affine parameters. There should be no difference if you use multiple batchnorms with `affine=False`.

**Comment by leckie-chn** [comment]
Thank you for your timely reply :）
