### ISSUE TITLE
RNN PTB model search converges to local optimum with a high perplexity number 

### ISSUE THREAD

**Issue by leckie-chn** [quark0/darts#29]
Hi,

I'm trying to reproduce the RNN arch search over PTB. I run `train_search.py` with default settings, but got high perplexity number, and seems that the arch search converges to a local optimum at a early stage.

So is it just bad luck(try different rand seeds), or the arch needs to be re-evaluated from scratch, or there's something unnoticed?
[log.txt](https://github.com/quark0/darts/files/2265480/log.txt)

**Comment by leckie-chn** [comment]
BTW, one more question.
The gate operation applied was kind of different from what is known as rnn gates:
* https://github.com/quark0/darts/blob/d922492be3c71b33be98c7e35871013e0e761286/rnn/model.py#L85
* https://github.com/quark0/darts/blob/d922492be3c71b33be98c7e35871013e0e761286/rnn/model_search.py#L37
also different from the ENAS paper. So any suggestions?

**Comment by quark0** [comment]
You will need to retrain from scratch as the weights during architecture search are far from convergence. It's expected to get high perplexity at this time. The search process for RNNs is of high variance, as shown in Figure 3 of the paper. In our case, we've repeated the search for 4 times with different random seeds.

For your second question, they the same if you look at [L84](https://github.com/quark0/darts/blob/d922492be3c71b33be98c7e35871013e0e761286/rnn/model.py#L84) of `model.py`, where `h = fn(h)`. Also note that `s + c*(h-s)` and `(1-c)*s_prev+c*h` are always equivalent, but the former is more efficient.
