### ISSUE TITLE
How to save and load pytorch model

### ISSUE THREAD

**Issue by Rajat2712** [quark0/darts#30]
Hey can you help me with saving the final model which can be load directly on a system without requiring other files.
Since the model is only saving the weights i.e. model.state_dict() so i have updated that line for saving the complete model not only the state_dict but still to load the model it requires all other custom py files like model_search ,  architecture and genotypes.

**Comment by quark0** [comment]
I can't provide help with specific use cases. Perhaps just pickle the genotypes etc. along with the weights.

**Comment by marsggbo** [comment]
> Even after i pickle everything the model is save is different from usual model.
> I cannot understand the usage of genotypes and how to use the create the final model.

HI dude! Have you solved this problem?
