### ISSUE TITLE
Why FactorizedReduce use two convolutional layers?

### ISSUE THREAD

**Issue by D-X-Y** [quark0/darts#38]
Hi,
I saw that `https://github.com/quark0/darts/blob/master/cnn/operations.py#L90` use two convolutional layers. May I know why use this structure instead of one convolutional layer with the output dimension twice?

Best Regards,

**Comment by quark0** [comment]
I simply followed the TF implementations of [NASNet](https://github.com/tensorflow/models/blob/23b5b4227dfa1b23d7c21f0dfaf0951b16671f43/research/slim/nets/nasnet/nasnet_utils.py#L87) and [AmoebaNet](https://github.com/tensorflow/tpu/blob/a6d2e2411ac3519034844c3aa8a26426e86d9e8d/models/official/amoeba_net/network_utils.py#L117). Perhaps they want more coverage in the spatial dimensions when the kernel size is 1x1.

**Comment by D-X-Y** [comment]
Got it. Thanks a lot.
