### ISSUE TITLE
The difference between training and testing?

### ISSUE THREAD

**Issue by D-X-Y** [quark0/darts#39]
Hi,

It seems that during training, the cell uses a weighted sum over all edges to generate features from one node to another node, as `https://github.com/quark0/darts/blob/master/cnn/model_search.py#L21`. However, during testing, you select 2 edges with the maximum values to sum, as `https://github.com/quark0/darts/blob/master/cnn/model_search.py#L142`. May I ask, why you choose 2 edges rather than another number?

Best Regards,

**Comment by quark0** [comment]
This is for fair comparison with existing models, e.g., AmoebaNet, NASNet and PNASNet.
