### ISSUE TITLE
drop_path_prob = 0.2 or 0.3?

### ISSUE THREAD

**Issue by D-X-Y** [quark0/darts#42]
Hi,

In the paper, it said that "path dropout of probability 0.3", but in the `cnn/train.py` the default value of drop_path_prob is 0.2. May I ask whether the experiments in the paper use 0.2 or 0.3? And does it affect the results a lot?

Best Regards,

**Comment by quark0** [comment]
Please use 0.2 as in the code (we'll fix the typo in the paper). Whether it's 0.2 or 0.3 won't make a big difference, but it's important to have some non-zero drop out probabilities there.
