### ISSUE TITLE
ImageNet Training Time and Performance?

### ISSUE THREAD

**Issue by D-X-Y** [quark0/darts#44]
Hi,

In the python code, the default setting of epochs for ImageNet is 1000, while in the paper, it says that the training epoch is 250. Does the 26.9% top-1 error come from 1000 epochs or 250 epochs? If it comes from 250 epochs, how about the performance of training 1000 epochs?

**Comment by quark0** [comment]
The performance would plateau before epoch 250, so we early stopped there.
