### ISSUE TITLE
Question about architecture derivation

### ISSUE THREAD

**Issue by cys4** [quark0/darts#45]
First, thank you for sharing this great work!

I have something unclear about choosing top-2 strongest edges for each node in the CNN case. 
From the paper and the code, my understanding of this selection is to take two edges whose highest non-zero operation probabilities are larger than than other edges'.

But, in your comment (https://github.com/quark0/darts/issues/32#issuecomment-413081130), the selection seems to depend on "sum of non-zero operations' probabilities" rather than "the highest among non-zero operations".

For example, if we assume we have one edge from the following two, which should be chosen? 
(To me, it seems the paper & code selects (1) while the github comment tells (2).)

(1) {zero: 0.4, conv: 0.5, pool: 0.1} 
(2) {zero: 0.3, conv: 0.35, pool: 0.35}

Thanks.

**Comment by quark0** [comment]
Thanks for the question. Please follow the paper & code, which would select edge (1).

My previous comment simply says that p(conv) = 0.5 in edge (1) can be factorized as (1-0.4) * (0.5 / (0.5 + 0.1)), namely gross_prob_of_non-zero_ops * conditional_prob_of_a_particular_op.

**Comment by cys4** [comment]
Thank you for the clarification.
