### ISSUE TITLE
The code to calculate the multiply-add operations?

### ISSUE THREAD

**Issue by D-X-Y** [quark0/darts#46]
In section 3.4.1, it is said that " the number of multiply-add operations in the model is restricted to be less than 600M". Would you mind to provide the code to calculate the number of multiply-add operations?

Best Regards,

**Comment by D-X-Y** [comment]
I found one that works well. https://github.com/warmspringwinds/pytorch-segmentation-detection/blob/master/pytorch_segmentation_detection/utils/flops_benchmark.py

**Comment by quark0** [comment]
Thank for the pointer!

**Comment by D-X-Y** [comment]
Hi @quark0 , it is very strange, that I use your DARTS_V2 and obtain the flops of 523 M, which is lower than 570M reported in your paper. I consider the flops of conv and fc layers. Do you consider other operations?

**Comment by dragen1860** [comment]
@D-X-Y heihei

**Comment by chakkritte** [comment]
Hi @D-X-Y,
I also have problems like you. I use https://github.com/sovrasov/flops-counter.pytorch to calculate multiply-add operations. I use DARTS_V2 then result of flops is 544.59 M.

Hi @quark0,
You had source-code of calculate multiply-add operations. Can you share this code to me?

**Comment by Z7zuqer** [comment]
> Hi @D-X-Y,
> I also have problems like you. I use https://github.com/sovrasov/flops-counter.pytorch to calculate multiply-add operations. I use DARTS_V2 then result of flops is 544.59 M.
> 
> Hi @quark0,
> You had source-code of calculate multiply-add operations. Can you share this code to me?

Hi, how do you test DARTS's FLOPS?

I used package `thop` as belows:
```
from thop import profile
model =torch.load('checkpoint.pth.tar')
input = torch.randn(1, 3, 224, 224)
flops, params = profile(model, inputs=(input, ))
```

Like codes up, we get DARTS's FLOPS is 952M,

Should we delete *Aux-Head* , *BatchNorm*, *ReLU* and other modules like this?

Really appreciate that you can reply.

**Comment by aaron851113** [comment]
Hi @chakkritte  
I tried both your method , but got error code as 
`File "/root/notebooks/darts-multi_gpu/cnn/operations.py", line 102, in forward
    out = torch.cat([self.conv_1(x), self.conv_2(x[:,:,1:,1:])], dim=1)
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 1. Got 2 and 1 in dimension 2 at /opt/conda/conda-bld/pytorch_1544197736932/work/aten/src/TH/generic/THTensorMoreMath.cpp:1333`

Hi @mapleam . I am aslo calculating FLOPs for DARTS. 
I tried both your method , but got error code as 
`TypeError: forward() takes 2 positional arguments but 109 were given`

Could you share your method detailed ?

**Comment by chakkritte** [comment]
Hi @aaron851113,

This is working for me.

```
import torch
import utils
import torch.nn as nn
import genotypes
from torch.autograd import Variable
from model import NetworkImageNet as Network
from ptflops import get_model_complexity_info

genotype = eval("genotypes.%s" % "DARTS")
model = Network(48, 1000, 14, False, genotype)

flops, params = get_model_complexity_info(model, (224, 224), as_strings=True, print_per_layer_stat=True)
print('Flops:  {}'.format(flops))
print('Params: ' + params)
```

**Comment by Z7zuqer** [comment]
> Hi @chakkritte
> I tried both your method , but got error code as
> `File "/root/notebooks/darts-multi_gpu/cnn/operations.py", line 102, in forward out = torch.cat([self.conv_1(x), self.conv_2(x[:,:,1:,1:])], dim=1) RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 1. Got 2 and 1 in dimension 2 at /opt/conda/conda-bld/pytorch_1544197736932/work/aten/src/TH/generic/THTensorMoreMath.cpp:1333`
> 
> Hi @mapleam . I am aslo calculating FLOPs for DARTS.
> I tried both your method , but got error code as
> `TypeError: forward() takes 2 positional arguments but 109 were given`
> 
> Could you share your method detailed ?

Hi, 

That package has updated so it couldn't run.

And I have solved my question about FLOPs of DARTS. We made a mistake by setting stem_multiplier=3, so when we construct the network using DARTS cell and our codebase, FLOPs is about 900M. And that's why I am concerned about how to test FLOPs of DARTS model.

And it's easy to make mistake here. We should clarify in our codebase whether stem_multiplier in cifar and ImageNet are the smae. (Actually they'are not the same.)

Best.

**Comment by aaron851113** [comment]
Thanks for @mapleam , @chakkritte !!!
I calculate it successfully by `from ptflops import get_model_complexity_info` .
But I got the same condition as chakkritte .
DARTS FLOPs is about 544M .

**Comment by harisgulzar1** [comment]
> I used package `thop` as belows:
> 
> ```
> from thop import profile
> model =torch.load('checkpoint.pth.tar')
> input = torch.randn(1, 3, 224, 224)
> flops, params = profile(model, inputs=(input, ))
> ```
Thank you.
It worked like a charm for me.
