### ISSUE TITLE
Validation phase code

### ISSUE THREAD

**Issue by vardaan123** [quark0/darts#47]
The code doesn't take argmax of the operations /best two of the edges in the inference phase of the script https://github.com/quark0/darts/blob/master/cnn/train_search.py
How does this correspond to the actual inference? There is a possibility that the performance might degrade significantly when you discretize the architecture.

**Comment by quark0** [comment]
The genotypes reported by `train_search.py` are obtained by taking the argmax. You need to train them (the discretized architectures) from scratch using `train.py` as the final evaluation step.

**Comment by YANGWAGN** [comment]
However, I don,t find how to load the weight obtained by train_search.py in train.py.  Thank you !
