### ISSUE TITLE
FC/Dense and MLP capabilities

### ISSUE THREAD

**Issue by jaggzh** [quark0/darts#48]
How can we:
1. Apply this to plain MLP's?
2. Handle the addition of fully-connected layers (eg. after a CNN)?
3. Use for single or multivariable regression?

**Comment by quark0** [comment]
1. One may learn to include/remove a dense layer by defining a mixture of the skip op and the fully-connected op.
2. Same as above.
3. Two steps: (i) define a search space (include candidate ops that you think is meaningful for regression tasks) (ii) modify the loss function as MSE.
