### ISSUE TITLE
architect.py

### ISSUE THREAD

**Issue by SivanDoveh** [quark0/darts#52]
Hi, wonderful work!

I have a question regarding architect.py, hessian_vector_product.
From my understanding R is epsilon, grad_p,grad_n are gradients of loss for w+- (positive and negative) 
Why in grad_n calculation you do p.data.sub_(**2*R**, v) And not p.data.sub_(**R**, v)?

Thanks!!

**Comment by quark0** [comment]
Note `p` was [modified](https://github.com/quark0/darts/blob/f276dd346a09ae3160f8e3aca5c7b193fda1da37/cnn/architect.py#L79) in place, so here we are actually doing `w^+ - 2d = w^-` instead of `w - d = w^-`.
