### ISSUE TITLE
what's the function of `target.cuda(async=True)`?

### ISSUE THREAD

**Issue by dragen1860** [quark0/darts#64]
Dear author:
  Thank you for sharing.
  I wonder the function of `async=True` in `target.cuda(async=True)` code. I rarely use the `async=True` therefore i know few about its usage.
Could you kindly explain it to me? Thank you.

**Comment by cclauss** [comment]
#25 has the answer to your question.   Since torch 0.4, __async__ is deprecated in cuda because it is a reserved word in Python >= 3.7 so as #25 advocates, __non_blocking__ should be used instead.

**Comment by stjamesmichael** [comment]
hi, I can't run alphapose project on my windows 10. 
I installed cuda 10.2 and add environment to path "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\bin" and add dll file of intel-openmp-2018.0.3-0.tar to the bin path.
I used pytorch version 0.4.0
but error occured. error is following:
G:\work\python\AlphaPose>python webcam_demo.py --vis
Traceback (most recent call last):
  File "webcam_demo.py", line 11, in <module>
    from dataloader_webcam import WebcamLoader, DetectionLoader, DetectionProcessor, DataWriter, crop_from_dets, Mscoco
  File "G:\work\python\AlphaPose\dataloader_webcam.py", line 7, in <module>
    from SPPE.src.utils.img import load_image, cropBox, im_to_torch
  File "G:\work\python\AlphaPose\SPPE\src\utils\img.py", line 269
    x = x.cuda(async=True)
                   ^
SyntaxError: invalid syntax

Why this happened?
Please help me.

**Comment by cclauss** [comment]
`async` is a reserved keyword in Python >= 3.7 so it is a SyntaxError to use it in this way.  The word `async` must be changed to `non_blocking` for your code to work on current versions of Python.
