### ISSUE TITLE
Derivation from Eq 5 to Eq 6 in the paper?

### ISSUE THREAD

**Issue by dragen1860** [quark0/darts#69]
Dear all:
  I tried my best to understand the derivation process from Eq 5 -> Eq 6 and from Eq. 6 -> Eq. 7:

Eq. 5:
![image](https://user-images.githubusercontent.com/4252555/52097494-54cbe100-261f-11e9-819b-d93e15d2f3e6.png)
Eq. 6:
![image](https://user-images.githubusercontent.com/4252555/52097496-5dbcb280-261f-11e9-8bb2-24352077a0ea.png)
Eq. 7:
![image](https://user-images.githubusercontent.com/4252555/52097499-6614ed80-261f-11e9-9514-6e5f70e09fd7.png)

But i still feel confused about how it is derived?
Could anyone help me illustrate the derivation process?
Thank you so much.

**Comment by zlheui** [comment]
Hi, the following contains my derivation, hope it can help you. Thanks.
![darts-answer](https://user-images.githubusercontent.com/8085821/52106435-b85d0b00-262d-11e9-9833-cef6e74334b2.PNG)
